name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Get Cache Directory
      id: cache-dir
      run: |
          echo ::set-output name=dir::%CD%
      shell: cmd
    - name: Install Dependencies
      run: vcpkg install embree3
      shell: cmd
    - name: Build Release Version
      run: make release
      shell: cmd
    - name: Build Debug Version
      run: make debug
      shell: cmd
